import sqlite3
conn = sqlite3.connect('/app/tradingagents.db')
c = conn.cursor()
c.execute("SELECT market_report, news_report, fundamentals_report, macro_report, smart_money_report, game_theory_report, decision, direction, confidence FROM reports WHERE symbol = '002467.SZ' ORDER BY created_at DESC LIMIT 1")
r = c.fetchone()
if r:
    print("=== Market Report ===")
    print(r[0][:1000] if r[0] else "None")
    print("\n=== News Report ===")
    print(r[1][:1000] if r[1] else "None")
    print("\n=== Fundamentals Report ===")
    print(r[2][:1000] if r[2] else "None")
    print("\n=== Macro Report ===")
    print(r[3][:1000] if r[3] else "None")
    print("\n=== Smart Money Report ===")
    print(r[4][:1000] if r[4] else "None")
    print("\n=== Game Theory Report ===")
    print(r[5][:1000] if r[5] else "None")
    print("\n=== Decision ===")
    print("Decision:", r[6])
    print("Direction:", r[7])
    print("Confidence:", r[8])
conn.close()
